[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9.16"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
